# Generated by Django 5.2.7 on 2025-11-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListOfTrusedUers',
            new_name='ListOfTrustedUsers',
        ),
    ]
