# Generated by Django 5.2.7 on 2025-10-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_credencial_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='otpCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='credential',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
