# Generated by Django 5.2.7 on 2025-11-02 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_listoftruseduers_listoftrustedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='core.credential')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_credentials', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('credential', 'shared_with'), name='unique_credential_sharing')],
            },
        ),
    ]
